"""Problem #71: DailyCodingProblems.com

Using a function rand7() that returns an integer from 1 to 7 (inclusive) 
with uniform probability, implement a function rand5() that returns an 
integer from 1 to 5 (inclusive).

"""

def rand5():
  """Returns a random number from 1 to 5 (inclusive)
  
  This has a weighted function that has a higher probability of returning
  the numbers 1 and 2. However this saves on runtime for the function
  as runtime was not specified but it only contains a single call to
  rand7() whose runtime is unknown.
  
  Returns:
    A random number from range 1 to 5 (inclusive)
    
  """
  retVal = rand7()
  if retVal < 6:
    return retVal
  else:
    return retVal % 5 + 1
    

def rand5():
  """Returns a random number from 1 to 5 (inclusive)
  
  Due to the property from the given function of rand7() this
  function also has uniform probability of getting a number 
  from 1 to 5. However, this function can run forever if there
  is never a number that is less than 5 generated by rand7().
  
  Returns:
    A random number from range 1 to 5 (inclusive)
    
  """
  retVal = rand7()
  while retVal > 5:
    retVal = rand7()
   return retVal
 
